### ISSUE TITLE
I love this, will this be actively developed?

### ISSUE THREAD

**Issue by CodeCurosity** [asmerkin/slideform#2]
I love this, will this be actively developed?

**Comment by asmerkin** [comment]
It's been in stand by for a while now, but yes, I'm planning to do some bug fixing / enhancements in the future. Any suggestions / feedback?

**Comment by mdtahmid** [comment]
@asmerkin Hi, is there a way to call a close() function on the form to close it? I ask this as I wish to use it as a modal form.

**Comment by asmerkin** [comment]
The form is intended to work as a full page form. So there is no default close function.

— Andrés Smerkin
